services:
  - type: web
    name: bowling-league
    env: node
    buildCommand: |
      npm ci
      npm run build
    startCommand: node server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
