services:
  - type: web
    name: bowling-league
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"   # ensures devDependencies (vite) are installed
